In [1]:
import pandas as pd

sales = pd.read_csv("../Week 1/sales_result.csv")

sales.head()

,sale_id,customer_name,product,category,quantity,price,city,sale_date,discount
0,1,Arun,Laptop,Electronics,1,55000.0,Bangalore,2026-08-01,10.0
1,3,Rahul,Chair,Furniture,1,4500.0,Mumbai,2026-08-05,NaN
2,4,Ananya,Keyboard,Electronics,1,2500.0,Bangalore,2026-08-07,8.0
3,5,Kiran,T-Shirt,Clothing,3,1200.0,Hyderabad,2026-08-10,15.0
4,6,Asha,Desk,Furniture,1,7000.0,Chennai,2026-08-12,NaN

In [2]:
sales.isnull().sum()

sale_id          0
customer_name    0
product          0
category         0
quantity         0
price            0
city             0
sale_date        0
discount         3
dtype: int64

In [3]:
sales["discount"] = sales["discount"].fillna(sales["discount"].mean())

sales

,sale_id,customer_name,product,category,quantity,price,city,sale_date,discount
0,1,Arun,Laptop,Electronics,1,55000.0,Bangalore,2026-08-01,10.0
1,3,Rahul,Chair,Furniture,1,4500.0,Mumbai,2026-08-05,10.0
2,4,Ananya,Keyboard,Electronics,1,2500.0,Bangalore,2026-08-07,8.0
3,5,Kiran,T-Shirt,Clothing,3,1200.0,Hyderabad,2026-08-10,15.0
4,6,Asha,Desk,Furniture,1,7000.0,Chennai,2026-08-12,10.0
5,7,Amit,Mobile,Electronics,1,25000.0,Mumbai,2026-08-15,10.0
6,8,Sneha,Jeans,Clothing,2,3000.0,Bangalore,2026-08-18,5.0
7,9,Vikram,Monitor,Electronics,1,15000.0,Delhi,2026-08-20,10.0
8,10,Divya,Table,Furniture,1,6000.0,Hyderabad,2026-08-22,12.0

In [4]:
sales.duplicated().sum()

np.int64(0)

In [5]:
Q1 = sales["price"].quantile(0.25)
Q3 = sales["price"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

sales[(sales["price"] < lower) | (sales["price"] > upper)]

,sale_id,customer_name,product,category,quantity,price,city,sale_date,discount
0,1,Arun,Laptop,Electronics,1,55000.0,Bangalore,2026-08-01,10.0

In [6]:
sales["price"] = sales["price"].clip(lower=lower, upper=upper)

sales.head()

,sale_id,customer_name,product,category,quantity,price,city,sale_date,discount
0,1,Arun,Laptop,Electronics,1,33000.0,Bangalore,2026-08-01,10.0
1,3,Rahul,Chair,Furniture,1,4500.0,Mumbai,2026-08-05,10.0
2,4,Ananya,Keyboard,Electronics,1,2500.0,Bangalore,2026-08-07,8.0
3,5,Kiran,T-Shirt,Clothing,3,1200.0,Hyderabad,2026-08-10,15.0
4,6,Asha,Desk,Furniture,1,7000.0,Chennai,2026-08-12,10.0

In [7]:
text_columns = ["customer_name", "product", "category", "city"]

for col in text_columns:
    sales[col] = sales[col].str.strip().str.title()

sales.head()

,sale_id,customer_name,product,category,quantity,price,city,sale_date,discount
0,1,Arun,Laptop,Electronics,1,33000.0,Bangalore,2026-08-01,10.0
1,3,Rahul,Chair,Furniture,1,4500.0,Mumbai,2026-08-05,10.0
2,4,Ananya,Keyboard,Electronics,1,2500.0,Bangalore,2026-08-07,8.0
3,5,Kiran,T-Shirt,Clothing,3,1200.0,Hyderabad,2026-08-10,15.0
4,6,Asha,Desk,Furniture,1,7000.0,Chennai,2026-08-12,10.0

In [8]:
sales.isnull().sum()

sale_id          0
customer_name    0
product          0
category         0
quantity         0
price            0
city             0
sale_date        0
discount         0
dtype: int64

In [9]:
print("AFTER CLEANING")
print("Missing values:", sales.isnull().sum().sum())
print("Duplicate rows:", sales.duplicated().sum())
print("Total rows:", len(sales))

AFTER CLEANING
Missing values: 0
Duplicate rows: 0
Total rows: 9

In [10]:
sales.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Data Cleaning Log

## Dataset
Sales transaction dataset

## Cleaning Steps

### 1. Missing Values
- Checked missing values using `isnull().sum()`.
- The `discount` column had 3 missing values.
- Missing discount values were replaced using the mean of the available discount values.

### 2. Duplicate Records
- Checked duplicate rows using `duplicated().sum()`.
- Found 0 duplicate rows.
- No duplicate records were removed.

### 3. Outliers
- Used the IQR method to detect outliers in the `price` column.
- Extreme price values were capped using the IQR lower and upper limits.

### 4. Text Standardization
- Removed extra whitespace from text columns.
- Standardized text using title case for:
  - Customer name
  - Product
  - Category
  - City

## Before vs After

| Quality Check | Before Cleaning | After Cleaning |
|---|---:|---:|
| Missing values | 3 | 0 |
| Duplicate rows | 0 | 0 |
| Total rows | 9 | 9 |

## Conclusion
The dataset was cleaned by handling missing values, checking duplicates, treating price outliers, and standardizing text values. The final dataset contains 9 records with no missing values or duplicate rows.